version: '3.8'

services:
  backend:
    image: phamtrongtinh/mern-backend:1.0
    ports:
      - "5000:5000"
    env_file:
      - ./mern-demo/env
    restart: always

  frontend:
    image: phamtrongtinh/mern-frontend:2.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always